Plant Routes
calebbarzee/spruce_moose_backend pull request #1
Opened 2023-03-07 18:04 UTC by spencer-rafada

- I merged main to my branch and run the formatting and linter so there will be no merge conflicts now.
- Added Plant routes and refactored it already

2023-03-07 23:16 UTC, jjossie approved these changes
Love it, high quality stuff Spencer 🤝

2023-03-07 23:48 UTC, Jacksonckc requested changes
Please take a look at my questions thank you

2023-03-07 23:48 UTC, Jacksonckc commented on src/routes/plant.ts
> +plantRouter.delete('/:plantId', requiresAuth());
is this supposed to be empty?

2023-03-07 23:48 UTC, Jacksonckc commented on src/routes/plant.ts
> +    const result = await addPlant(newPlant);
Are we going to check for the userLevel before we call this function? Or did you do it somewhere else already.

2023-03-07 23:48 UTC, Jacksonckc commented on src/routes/plant.ts
> +      const result = await updatePlant(filter, plant);
Same question as above

2023-03-08 01:06 UTC, spencer-rafada commented on src/routes/plant.ts
> +plantRouter.delete('/:plantId', requiresAuth());
I've worked on the functionality for this route.

2023-03-08 01:06 UTC, spencer-rafada commented on src/routes/plant.ts
> +      const result = await updatePlant(filter, plant);
I just finished adding the check for userLevel for PUT, POST, and DELETE route.

2023-03-09 15:20 UTC, merged